### ISSUE TITLE
摸鱼怎么能少得了网文?

### ISSUE THREAD

**Issue by ForkFG** [TheThreeDog/TouchFish#12]
本人（学生）正在编写的命令行读小说工具 [TerminalXbqg](https://github.com/ForkFG/TerminalXbqg)，支持换源、书架。正在做的功能（然而进度很慢）：目录、缓存、搜索。请求加入外部项目列表~

**Comment by TheThreeDog** [comment]
> 本人（学生）正在编写的命令行读小说工具 [TerminalXbqg](https://github.com/ForkFG/TerminalXbqg)，支持换源、书架。正在做的功能（然而进度很慢）：目录、缓存、搜索。请求加入外部项目列表~

可以可以！  马上搞上哈哈哈
