### ISSUE TITLE
网页版微信凉凉了

### ISSUE THREAD

**Issue by yinyuhang** [TheThreeDog/TouchFish#8]
RT

**Comment by TheThreeDog** [comment]
？  有吗  我这正常使用的呀

**Comment by JianboYan** [comment]
Please scan the QR code to log in.
Please press confirm on your phone.
Your wechat account may be LIMITED to log in WEB wechat, error info:
<error><ret>1203</ret><message>为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>
Start auto replying.
Traceback (most recent call last):
  File "Wechat.py", line 16, in <module>
    users = User.Users.instance()               # 初始化好友列表 (单例模式)
  File "/Users/uc/Downloads/TouchFish-master/WechatOfConsole/User.py", line 120, in instance
    Users._instance = Users(*args, **kwargs)
  File "/Users/uc/Downloads/TouchFish-master/WechatOfConsole/User.py", line 114, in __init__
    self.loadUserList(itchat.get_friends(),'f')             # 加载好友
  File "/Users/uc/Downloads/TouchFish-master/WechatOfConsole/User.py", line 173, in loadUserList
    self.selfUser = self.user_dict[0]
KeyError: 0

**Comment by peiht** [comment]
哈哈，我的也是不能登录

**Comment by TheThreeDog** [comment]
@peiht   @JianboYan  @yinyuhang 
要不试一试自己的微信在官方的微信网页版的网址能不能登录吧：
https://wx.qq.com/ 

如果这里不行的话，那这个工具也用不了恐怕

**Comment by peiht** [comment]
我试了，网页微信也不行，估计是腾讯做限制了

**Comment by yinyuhang** [comment]
> @peiht @JianboYan @yinyuhang
> 要不试一试自己的微信在官方的微信网页版的网址能不能登录吧：
> https://wx.qq.com/
> 
> 如果这里不行的话，那这个工具也用不了恐怕

嗯。做了限制，windows的只能用客户端登录~
